// Shared domain types. Content types mirror content/schema.json; storage types mirror src/db.ts.

export type EntryType = 'principle' | 'practice' | 'prompt' | 'script' | 'reminder';
export type Stage = 'open' | 'deepen' | 'depth_check' | 'suggestion' | 'ftl' | 'return';
export type SessionType =
  | 'morning-rehearsal' | 'act-as-if' | 'fear-screen' | 'ftl-deletion'
  | 'pre-sleep' | 'focus-flow' | 'goal-clarity' | 'habit-craving';

export interface Entry {
  id: string;
  key: string;            // `${source_id}/${id}` — stable reference used by Completion
  source_id: string;
  type: EntryType;
  title: string;
  body: string;
  duration_sec: number;
  tags: string[];
  timestamp: string;
  hypnosis: boolean;
  stage?: Stage;
  session_types?: SessionType[];
}

export interface SourceMeta {
  id: string; title: string; url: string; creator: string; date_added: string;
}

export interface TeacherView {
  id: string; source_id?: string; timestamp?: string; claim: string; evidence_note: string;
}

// ---------- stored records ----------

/** Durable facts about the user, built by the Change Coach. Never written without confirmation. */
export interface ProfileFact {
  id: string;
  kind: 'goal' | 'identity' | 'struggle' | 'trigger' | 'language' | 'note';
  text: string;
  created_at: number;
  source: 'coach' | 'manual';
  /** id of the ChatMessage/conversation this was extracted from, for provenance */
  from_conversation?: string;
}

export interface Profile {
  id: 'me';
  facts: ProfileFact[];
  updated_at: number;
}

export interface ChatMessage {
  id: string;
  conversation_id: string;
  role: 'user' | 'guide';
  text: string;
  created_at: number;
}

/** A composed session: an ordered list of script steps plus the plain-language suggestion list. */
export interface SessionPlan {
  id: string;
  title: string;
  session_type: SessionType;
  target_sec: number;
  steps: SessionStep[];
  /** Shown verbatim in Preview. Nothing is delivered that is not listed here. */
  suggestions: string[];
  origin: 'library' | 'coach';
  created_at: number;
  /** Set when generated by the Coach, so the user can see why a session says what it says. */
  rationale?: string;
}

export interface SessionStep {
  stage: Stage;
  title: string;
  body: string;
  duration_sec: number;
  entry_key?: string;
}

export interface Completion {
  id: string;
  /** entry key, session plan id, or a routine item id */
  ref: string;
  kind: 'session' | 'practice' | 'prompt' | 'checkin';
  title: string;
  date: string;              // YYYY-MM-DD, local
  started_at: number;
  ended_at: number;
  seconds: number;
  finished: boolean;         // false when stopped early — still recorded, never punished
  mood_before?: number;      // 1..5
  mood_after?: number;       // 1..5
}

export interface JournalEntry {
  id: string;
  date: string;
  prompt?: string;
  text: string;
  created_at: number;
  updated_at: number;
  linked_ref?: string;
}

export interface RoutineItem {
  id: string;
  slot: 'morning' | 'midday' | 'evening';
  kind: 'session' | 'practice' | 'prompt' | 'checkin';
  title: string;
  /** For sessions: the session type to compose. For practices/prompts: an entry key. */
  ref: string;
  minutes: number;
  enabled: boolean;
}

export interface Reminder {
  id: string;
  slot: 'morning' | 'midday' | 'evening';
  time: string;   // HH:MM
  text: string;
  enabled: boolean;
}

export interface Settings {
  id: 'settings';
  tts_enabled: boolean;
  tts_voice_uri: string | null;
  tts_rate: number;          // 0.5..1.2
  pace: 'slow' | 'natural' | 'brisk';
  ambient: 'off' | 'hum' | 'rain' | 'air';
  ambient_volume: number;    // 0..1
  reminders: Reminder[];
  reminders_enabled: boolean;
  quiet_start: string;       // HH:MM
  quiet_end: string;         // HH:MM
  max_reminders_per_day: number;  // hard cap 8
  routine: RoutineItem[];
  onboarded: boolean;
  /** Suppresses the pre-session safety notice once acknowledged. */
  safety_ack: boolean;
}

export interface QueuedSession {
  id: string;
  plan: SessionPlan;
  slot: 'morning' | 'midday' | 'evening' | 'next';
  created_at: number;
}
